dist: xenial
language: python
env:
  global:
  - ENVIRONMENT=test
  - BOT_NICKNAME="bamthebot"
  - COMMAND_PREFIX="!"
  - BANGS_ENDPOINT="http://ubuntu@ec2-13-58-112-69.us-east-2.compute.amazonaws.com/bot/api/bangs/"
  - USERS_ENDPOINT="http://ubuntu@ec2-13-58-112-69.us-east-2.compute.amazonaws.com/bot/api/twitch_users/"
  - BANGS_TOKEN="TODO"
  - USERS_TOKEN="TODO"
  - TWITCH_URI="wss://irc-ws.chat.twitch.tv:443"
  - BOTMASTER_RUN="yes"
services:
- docker
script:
- docker-compose -f docker-compose.test.yaml run web
deploy:
- provider: script
  skip_cleanup: true
  script: cd scripts && bash deploy.sh master
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: cd scripts && bash deploy.sh stage
  on:
    branch: stage
