version: '3.3'
services:
  web:
    build: .
    restart: always
    environment:
    - BOT_NICKNAME=$BOT_NICKNAME
    - BOT_TOKEN=$BOT_TOKEN
    - COMMAND_PREFIX=$COMMAND_PREFIX
    - NOT_FOUND_RESPONSE=$NOT_FOUND_RESPONSE
    - BANGS_ENDPOINT=$BANGS_ENDPOINT
    - USERS_ENDPOINT=$USERS_ENDPOINT
    - BANGS_TOKEN=$BANGS_TOKEN
    - TWITCH_URI=$TWITCH_URI
    volumes:
    - ./bambot:/home/bam/bambot/
    - ./tests:/home/bam/bambot/tests
