version: '3.3'
services:
  web:
    restart: always
    image: twitchbambot/bambot:master
    environment:
    - BOT_NICKNAME
    - BOT_TOKEN
    - COMMAND_PREFIX
    - NOT_FOUND_RESPONSE
    - BANGS_ENDPOINT
    - USERS_ENDPOINT
    - BANGS_TOKEN
    - USERS_TOKEN
    - TWITCH_URI
